Traceback (most recent call last):
  File "/Users/rafamtz/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/rafamtz/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/rafamtz/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/rafamtz/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/rafamtz/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/rafamtz/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/rafamtz/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/rafamtz/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pagina[0:10000]
pes1=re.findall(r"<p>.+</p>",pagina)
len(pes1)
pes1[0]
soup = BeautifulSoup(pagina, 'html.parser')
pes=soup.findAll("p")
len(pes)
pes[0:3]
pes1=re.findall(r"<p.*/p.+>",pagina)
print(len(pes1))
pes1[0:3]
enlaces
divs
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-3-4507eb0d42a3>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mpagina[0m[0;34m[[0m[0;36m0[0m[0;34m:[0m[0;36m10000[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mpes1[0m[0;34m=[0m[0mre[0m[0;34m.[0m[0mfindall[0m[0;34m([0m[0;34mr"<p>.+</p>"[0m[0;34m,[0m[0mpagina[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mlen[0m[0;34m([0m[0mpes1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mpes1[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0msoup[0m [0;34m=[0m [0mBeautifulSoup[0m[0;34m([0m[0mpagina[0m[0;34m,[0m [0;34m'html.parser'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 're' is not defined
NameError: name 're' is not defined

